### ISSUE TITLE
Enable generating random ports with host port mapping

### ISSUE THREAD

**Issue by gyliu513** [projectcalico/k8s-policy#110]
This is a problem that I found when testing https://github.com/projectcalico/k8s-policy/issues/109 . The problem is that when I use `hostport` mapping feature in calico, I was always need to specify pods `hostPort` as following in `ports` section.

```
root@k8s001:~/calico2.4# cat pod.yaml
apiVersion: v1
kind: Pod
metadata:
  name: nginx-host
spec:
  containers:
  - image: nginx
    imagePullPolicy: IfNotPresent
    name: nginx-host
    ports:
    - containerPort: 80
      hostPort: 80
  restartPolicy: Always
root@k8s001:~/calico2.4# kubectl create -f ./pod.yaml
pod "nginx-host" created
root@k8s001:~/calico2.4# kubectl get pods -owide
NAME                      READY     STATUS    RESTARTS   AGE       IP                NODE
nginx-host                1/1       Running   0          9s        192.168.124.143   k8s004
```

The problem is that if one node start two such pods, only one pod can be started and another pod will be pending always as it cannot get the same port again.

## Expected Behavior

Enable `host port mapping` can generate the host port randomly so that end user will not need to specify the host port.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Kubernetes version (`kubectl version`):
* Manifest file used to deploy k8s policy:
* Operating System and version:
* Link to your project (optional):

/cc @caseydavenport @gunjan5

**Comment by tmjd** [comment]
I don't think this should be a Calico issue.  Calico is not doing the port mapping, it is the portmap plugin that sets that up.  So this issue should probably be against the portmap plugin.
@gunjan5 or @caseydavenport If you agree then I think this issue should be closed.

**Comment by gyliu513** [comment]
@tmjd if that is the case, instead of closing this one, shall we move this issue to `cni-plugin` directly?

**Comment by tmjd** [comment]
If you are talking about projectcalico/cni-plugin I still do not think that is the correct repo.  It is the repo where you got the portmap plugin. I think https://github.com/containernetworking/plugins is where an issue like that should be, or it may even need to go against kubernetes also because I don't know if there are allowances for a random port.

**Comment by gyliu513** [comment]
Thanks @tmjd , yes, this seems to be an issue for https://github.com/containernetworking/plugins , will try to move this issue there.
