### ISSUE TITLE
Use upstream portmap plugin releases (when available)

### ISSUE THREAD

**Issue by caseydavenport** [projectcalico/k8s-policy#111]
We currently host our own build of the portmap plugin to include in `calico/cni`.  We should switch to the upstream release when v0.6.0 comes out.

**Comment by gunjan5** [comment]
why is this issue in this repo? shouldn't it be in calico/cni-plugin?

**Comment by tmjd** [comment]
I pinged Casey over slack just a few minutes ago asking the same thing.

**Comment by caseydavenport** [comment]
Sigh.  Lost track of where I was.
