### ISSUE TITLE
Network Policies not working in Calico 2.4 with k8s 1.7 and Flannel as CNI 

### ISSUE THREAD

**Issue by kanor1306** [projectcalico/k8s-policy#118]
I am running a standard hosted Kubernetes, where flannel runs as a system daemon and Calico as a deployment with tls secured etcd and RBAC enabled. You can find the manifest at the end of this issue.

The deployment succeeds, all the pods run and I don't see any error in the logs of any pod, but when I try to follow the tutorial for the advanced policies in https://docs.projectcalico.org/v2.4/getting-started/kubernetes/tutorials/advanced-policy they don't seem to work. 

I am not sure if I am missing something, but I followed the steps several times, and I couldn't make it work using the Kubernetes NetworkPolicies.

## Expected Behavior
Network policies work.

## Current Behavior
After executing the steps in the tutorial https://docs.projectcalico.org/v2.4/getting-started/kubernetes/tutorials/advanced-policy no NetworkPolicy seems to be applied.
Weird enough, if I follow https://docs.projectcalico.org/v2.2/getting-started/kubernetes/tutorials/advanced-policy it works, but I would like to avoid the deny all policy in a namespace, if possible, or at least not using the annotations.

## Steps to Reproduce (for bugs)
Following the tutorial, I already have two replicas of nginx running 

Step 1:
```
$ kubectl create -f - <<EOF
> kind: NetworkPolicy
> apiVersion: extensions/v1beta1
> metadata:
>   name: default-deny
>   namespace: advanced-policy-demo
> spec:
>   podSelector:
> EOF

$ calicoctl get profile -o wide
NAME                                         TAGS
k8s_ns.advanced-policy-demo   k8s_ns.advanced-policy-demo
k8s_ns.default                             k8s_ns.default
k8s_ns.kube-public                     k8s_ns.kube-public
k8s_ns.kube-system                   k8s_ns.kube-system
```

Step 2:
```
$ kubectl run --namespace=advanced-policy-demo access --rm -ti --image busybox /bin/sh
If you don't see a command prompt, try pressing enter.
/ # wget -q --timeout=5 nginx -O -
<!DOCTYPE html>
<html>
<head>
<title>Welcome to nginx!</title>
<style>
    body {
        width: 35em;
        margin: 0 auto;
        font-family: Tahoma, Verdana, Arial, sans-serif;
    }
</style>
</head>
<body>
<h1>Welcome to nginx!</h1>
<p>If you see this page, the nginx web server is successfully installed and
working. Further configuration is required.</p>

<p>For online documentation and support please refer to
<a href="http://nginx.org/">nginx.org</a>.<br/>
Commercial support is available at
<a href="http://nginx.com/">nginx.com</a>.</p>

<p><em>Thank you for using nginx.</em></p>
</body>
</html>
```

So this is the first problem, this request should timeout. Debugging a bit more I see this:

```
$ kubectl get netpol -n advanced-policy-demo
NAMESPACE                    NAME             POD-SELECTOR   AGE
advanced-policy-demo   default-deny   <none>               5m

$ kubectl get netpol -n advanced-policy-demo default-deny -o yaml
apiVersion: extensions/v1beta1
kind: NetworkPolicy
metadata:
  creationTimestamp: 2017-08-17T10:44:21Z
  generation: 1
  name: default-deny
  namespace: advanced-policy-demo
  resourceVersion: "15104063"
  selfLink: /apis/extensions/v1beta1/namespaces/advanced-policy-demo/networkpolicies/default-deny
  uid: 072643a5-8339-11e7-a6b1-005056010339
spec:
  podSelector: {}

$ calicoctl get profile k8s_ns.advanced-policy-demo -o yaml
- apiVersion: v1
  kind: profile
  metadata:
    name: k8s_ns.advanced-policy-demo
    tags:
    - k8s_ns.advanced-policy-demo
  spec:
    egress:
    - action: allow
      destination: {}
      source: {}
    ingress:
    - action: allow
      destination: {}
      source: {}
```

Which is totally wrong, as it is allowing all, and according to the tutorial it should be denying all. 
Executing the following commands of the tutorial lead tho this:

```
$ calicoctl get workloadendpoint
NODE                  ORCHESTRATOR   WORKLOAD                                                                   NAME
node1                  k8s                        kube-system.kube-dns-263189033-3m4jx                    eth0
node1                  k8s                        advanced-policy-demo.nginx-4217019353-156xx        eth0
node2                  k8s                        advanced-policy-demo.nginx-4217019353-n4jmd       eth0

$ calicoctl get wep --workload advanced-policy-demo.nginx-4217019353-156xx  -o yaml
- apiVersion: v1
  kind: workloadEndpoint
  metadata:
    activeInstanceID: 54b0fdf465bbc802282a748de1e78d6bea1069e8a336ba1799a2f1ba14202b5b
    labels:
      calico/k8s_ns: advanced-policy-demo
      pod-template-hash: "4217019353"
      run: nginx
    name: eth0
    node: node1
    orchestrator: k8s
    workload: advanced-policy-demo.nginx-4217019353-156xx
  spec:
    interfaceName: cali8f668a577ae
    ipNetworks:
    - <ip>
    mac: <mac_address>
    profiles:
    - k8s_ns.advanced-policy-demo

$ calicoctl get wep --workload advanced-policy-demo.nginx-4217019353-n4jmd  -o yaml
- apiVersion: v1
  kind: workloadEndpoint
  metadata:
    activeInstanceID: e7853f3b60c599453231a62f2e477c0ccb1c64b7a790e212308a6502d8239e35
    labels:
      calico/k8s_ns: advanced-policy-demo
      pod-template-hash: "4217019353"
      run: nginx
    name: eth0
    node: node2
    orchestrator: k8s
    workload: advanced-policy-demo.nginx-4217019353-n4jmd
  spec:
    interfaceName: cali2c96b483557
    ipNetworks:
    - <ip>
    mac: <mac_address>
    profiles:
    - k8s_ns.advanced-policy-demo
```

**This may be a different problem**

Apart from this, I also tried to ignore the namespace policy not being applied, remove it, and apply a specific network policy to a pod, like this:

```
$ kubectl create -f - <<EOF
kind: NetworkPolicy
apiVersion: extensions/v1beta1
metadata:
  name: access-nginx-other-only
  namespace: advanced-policy-demo
spec:
  podSelector:
    matchLabels:
      run: nginx
  ingress:
    - from:
      - podSelector:
          matchLabels:
            app: otherApplication
EOF

$ calicoctl get policies
NAME
advanced-policy-demo.access-nginx-other-only
k8s-policy-no-match

$ calicoctl get policies advanced-policy-demo.access-nginx-other-only -o yaml
- apiVersion: v1
  kind: policy
  metadata:
    name: advanced-policy-demo.access-nginx-other-only
  spec:
    egress:
    - action: allow
      destination: {}
      source: {}
    ingress:
    - action: allow
      destination: {}
      source:
        selector: app == 'other' && calico/k8s_ns == 'advanced-policy-demo'
    order: 1000
    selector: calico/k8s_ns == 'advanced-policy-demo' && run == 'nginx'
```

But still any pod can acces the nginx pod, even if it does not have the app label set to "other". According to this: https://kubernetes.io/docs/concepts/services-networking/network-policies/ this should work.

> By default, pods are non-isolated; they accept traffic from any source.
Pods become isolated by having a NetworkPolicy that selects them. Once there is any NetworkPolicy in a Namespace selecting a particular pod, that pod will reject any connections that are not allowed by any NetworkPolicy. (Other pods in the Namespace that are not selected by any NetworkPolicy will continue to accept all traffic.

## Context
I am trying to isolate some pods, without the need of putting them in a specific namespace. The reason for this is that in the current Kubernetes NetworkPolicies (created with kubectl), as far as i know, you only can create inter-pod NetworkPolicies if they are in the same namespace (of course with calicoctl it can be easily achieved), but not if they are in a different namespace. i.e. Pod A running in Namespace A, should not be able to access Pod B in namespace B, but Pod C in namespace A should be able.

## Your Environment

* Kubernetes version (`kubectl version`):  1.7.1
* Calico node: 2.4.1
* Kube-policy controller: 0.6.0
* cni: 1.10.0
* Manifest used to deploy Calico:  https://gist.github.com/kanor1306/022e526ba3d27a3d897cccb78d0807fb
* Manifest RBAC: https://gist.github.com/kanor1306/4d913aba763499c23f300e4a534f5ac6
* Operating System and version: Centos 7.3

**Comment by tmjd** [comment]
I see a couple things that I want to point out before trying to determine the root problem here.
1. In your context section you say that pods in one namespace cannot access pods in a different namespace. Inter-namespace traffic can certainly be allowed,  check out the Stars tutorial that sets up several namespaces and communication is allowed between them. https://docs.projectcalico.org/v2.4/getting-started/kubernetes/tutorials/stars-policy/
2. When you were looking for what enables the default deny you were looking at the profile for the namespace and I don't believe that is the correct object to look at, you should look at the policies (like the default-deny policy).  I could be wrong here but I don't think there is any use of profiles expected for K8s, previously it was used in K8s for implementing the default deny but that behavior has changed now.
3. You also mention isolating pods without putting them in a specific namespace, pods will always be in a namespace.  If one is not specified then they go into the default namespace.
4. Your calico.yaml still has the tolerations as annotations which I don't believe K8s supports anymore.  You can take a look at the tolerations and annotations in https://docs.projectcalico.org/v2.4/getting-started/kubernetes/installation/hosted/kubeadm/1.6/calico.yaml for an example.

One thing that I'm wondering is if you are running with a cluster where you have upgraded your calico manifest and applied that but perhaps not 'restarted' the calico pods (`kubectl delete -n kube-system pod <pod-name>`).  If you haven't you should restart each of the calico pods and see if that fixes things.

**Comment by kanor1306** [comment]
Thanks for the answer @tmjd, sorry for the delay, I was in holidays away from any computer!

1.  Yeah you are right, I wrote that part before realizing about the namespace selector. Basically I was expecting to have a way of selecting the namespace without using labels, just using the name (as it is done in the metadata). I found later the namespaceSelector, so I guess that I will apply some labels to my namespaces and it will be enough.

2. Oh man, you are so right on this... I totally understood the other way around the comment in https://github.com/projectcalico/k8s-policy/issues/108#issuecomment-318517824  :sweat:

3. I may have explained wrong this part. What I meant was that I would like to apply policies to pods, without the need of applying first a default policy to a namespace. i.e. I apply a policy to _pod A_ allowing _pod B_ to contact him. This would then deny access to _pod A_ from every pod except _pod B_ (at least that is what I understood in the quoted text from the Kubernetes documentation). And this didn't seem to work, but of course can be related with previous issues in my setup. I will try today to reproduce again all this taking into account your suggestions.

4. Oops, good catch, didn't notice it when taking the yamls from the Calico github, I will fix that also for my new tests just in case.

About restarting the pods, I think I have, but just in case as I am gonna try all of this again, I will make sure that I make a restart if it does not work.

Thanks for your insight, I will come back with some details about how it went in this second tryout.

**Comment by kanor1306** [comment]
I tried this again starting a cluster from scratch, and also restarting the calico pods after applying the policies, and I am still having exactly the same behavior as I had in my first message. When asking calicoctl to print the existing policies, this is what I get:

```
$ calicoctl get policies -o yaml
- apiVersion: v1
  kind: policy
  metadata:
    name: advanced-policy-demo.default-deny
  spec:
    egress:
    - action: allow
      destination: {}
      source: {}
    order: 1000
    selector: calico/k8s_ns == 'advanced-policy-demo'
- apiVersion: v1
  kind: policy
  metadata:
    name: k8s-policy-no-match
  spec:
    egress:
    - action: pass
      destination: {}
      source: {}
    ingress:
    - action: pass
      destination: {}
      source: {}
    order: 2000
    selector: has(calico/k8s_ns)

```

I am not sure anymore if that is what I should get, but I can access from the busybox running in that namespace to the nginx running in that same namespace.

My tests were again based in https://docs.projectcalico.org/v2.4/getting-started/kubernetes/tutorials/advanced-policy although I also tried the stars tutorial, with the same result, no blocking at all.

The logs of the calico-node pods only show INFO messages, no warnings, no errors. Same goes for the calico policy controller, although in this case I see something a bit weird. A message is repeated every 10 seconds. (note that the busybox "access" pod is stopped, as I went out of the terminal once I checked that it could access nginx)

```
2017-08-29 15:12:21,348 9 INFO Handled ADDED for Pod: ('advanced-policy-demo', 'access-2475823348-qb94r')
2017-08-29 15:12:21,363 9 INFO Handled MODIFIED for Pod: ('advanced-policy-demo', 'access-2475823348-qb94r')
2017-08-29 15:12:21,377 9 INFO Handled MODIFIED for Pod: ('advanced-policy-demo', 'access-2475823348-qb94r')
2017-08-29 15:12:23,742 9 INFO Handled MODIFIED for Pod: ('advanced-policy-demo', 'access-2475823348-qb94r')
2017-08-29 15:12:34,777 9 INFO Handled MODIFIED for Pod: ('advanced-policy-demo', 'access-2475823348-qb94r')
2017-08-29 15:12:35,963 9 INFO Handled MODIFIED for Pod: ('advanced-policy-demo', 'access-2475823348-qb94r')
2017-08-29 15:12:47,562 9 INFO Handled MODIFIED for Pod: ('advanced-policy-demo', 'access-2475823348-qb94r')
2017-08-29 15:12:47,564 9 INFO Handled DELETED for Pod: ('advanced-policy-demo', 'access-2475823348-qb94r')
2017-08-29 15:12:57,585 9 INFO Handled DELETED for Pod: ('advanced-policy-demo', 'access-2475823348-qb94r')
2017-08-29 15:13:07,636 9 INFO Handled DELETED for Pod: ('advanced-policy-demo', 'access-2475823348-qb94r')
2017-08-29 15:13:17,678 9 INFO Handled DELETED for Pod: ('advanced-policy-demo', 'access-2475823348-qb94r')
2017-08-29 15:13:27,725 9 INFO Handled DELETED for Pod: ('advanced-policy-demo', 'access-2475823348-qb94r')
.....every 10 secons...
2017-08-29 15:22:50,180 9 INFO Handled DELETED for Pod: ('advanced-policy-demo', 'access-2475823348-qb94r')
```

Not sure what can be happening here, everything seems ok, but it just does not work. Seeing that no more people complains about this, I can imagine that something is wrong with my setup.

**Comment by tmjd** [comment]
I just realized that you are using kube-policy-controller 0.6.0 and that is why you need the namespace annotation currently.  Actually my # 2 comment above was incorrect, I saw calico-node 2.4.1 and was thinking the Calico v2.4.1 behavior but actually the default deny is dependent on the kube-policy-controller version which for v2.4 should be v0.7.0.
Sorry I missed that the first time.

**Comment by kanor1306** [comment]
Yes, that was the problem! Now everything works as expected. Now I can finally use kubectl to handle my network policies. Thank you very much @tmjd!
