### ISSUE TITLE
Namespace Annotation has no effect if a policy exists

### ISSUE THREAD

**Issue by microadam** [projectcalico/k8s-policy#14]
Something I just noticed while playing with the now working examples, not sure if its actually intended behaviour or not.

With NS annotation disabled and no policys in place, everything can communicate. 
With NS annotation enabled and no policys, nothing can communicate
With NS annotation enabled and the `backend` policy in place, frontend can talk to backend, but backend cannot talk to backend
With NS annotation disabled and the `backend` policy in place, frontend can still talk to backend, but backend is still unable to talk to frontend.
With NS annotation disabled and the `backend` policy removed, all can talk to each other.

So it seems like when NS annotation is disabled, if a policy exists that policy will still be enforced. Is that the intended behaviour? I thought if you disabled the NS annotation, then regardless of what policies were in place, everything would be able to communicate. However that may just be an incorrect assumption.

Thanks a lot for your efforts on this project! Its looking really good and exactly what I was after

**Comment by caseydavenport** [comment]
Hey @microadam 

Yes, that is the intended behavior at the moment - `network-isolation` and `NetworkPolicies` operate independently of each other.

That isn't to say that this behavior is set in stone - definitely glad to hear / discuss use-cases one way or another.

**Comment by microadam** [comment]
Fair enough! Personally I think it would make sense that if you disable the NS annotation then it disables all of the current isolation policies on that NS. Can't think of an exact scenario but I can imagine that you might want to temporarily disable the isolation without having to delete all of your policies and then re-create them when if you want to re-enable them. 

Good to know how it works though, so thanks for clarifying!
