### ISSUE TITLE
fv tests failing on ppc64le

### ISSUE THREAD

**Issue by djlwilder** [projectcalico/k8s-policy#150]
The recently add fv test i(commit 3f5de8600733e2c19cdfa38a84afec9641d6db04) fail on ppc64le.

The issue is that in  tests/testutils/utils.go image names are hard coded for containers started by the tests.

func RunK8sApiserver(etcdIp string) *containers.Container {
...
               fmt.Sprintf("gcr.io/google_containers/hyperkube-amd64:%s", vK8sApiserver),
...

func RunEtcd() *containers.Container {
...
             "quay.io/coreos/etcd",
...

These are x86 images thus will not function on other archs.

## Possible Solution
I see two solutions:
1) Pass the container name to the test code as a environment variable that is set in the Makefile.
2) Pre-load the correct containers and tag them to match the hard coded names (yuck).

Any other ideas?
I will attempt to implement #1 

## Steps to Reproduce (for bugs)
In a ppc64le environment run:
ARCH=ppc64le make fv

**Comment by caseydavenport** [comment]
@ozdanborne could you take a look / help out with this one?

**Comment by caseydavenport** [comment]
Fixed in #153
