### ISSUE TITLE
network policy is not applied to profile？

### ISSUE THREAD

**Issue by reAsOn2010** [projectcalico/k8s-policy#29]
I tried to create namespaces and network policy in k8s, and the namespace annotation changes are indeed make effect. But when the network policy created, the policy controller only creates a policy entry but not updates the profile of the namespace?

I also checked the code, there is no profile update logic in `add_update_network_policy` function, is this expected?
```
yakumo@master:/opt/bin$ /opt/bin/etcdctl get /calico/v1/policy/tier/k8s-network-policy/policy/calico-k8s_ns.space1
{"id": "k8s_ns.space1", "outbound_rules": [{"action": "allow"}], "order": 2000, "inbound_rules": [{"action": "deny"}], "selector": "calico/k8s_ns == 'space1'"}
yakumo@master:/opt/bin$ /opt/bin/etcdctl get /calico/v1/policy/tier/k8s-network-policy/policy/space1.allow-all
{"id": "space1.allow-all", "outbound_rules": [{"action": "allow"}], "order": 1000, "inbound_rules": [{"action": "allow", "src_selector": "k8s_ns/label/name == 'space1'"}], "selector": "calico/k8s_ns == 'space1'"}
yakumo@master:/opt/bin$ /opt/bin/etcdctl get /calico/v1/policy/profile/k8s_ns.space1/rules
{"id": "k8s_ns.space1", "inbound_rules": [{"action": "deny"}], "outbound_rules": [{"action": "allow"}]}
```

**Comment by reAsOn2010** [comment]
Ok, I just checked the NetworkPolicies does work. But I prefer that I can see the rule using `calicoctl` command line tool, the profile rules just keep no change. Where can I find these NetworkPolicies related rules?

**Comment by caseydavenport** [comment]
@reAsOn2010 - Yeah, displaying / manipulating policies via `calicoctl` is something we're actively working on.

For now, you need to use `etcdctl` to view the contents of the `/calico/v1/policy/tier/k8s-network-policy/policy/<name>` entries in order to see what policies have been programmed.
