### ISSUE TITLE
Provide documentation how the policy controller actually works

### ISSUE THREAD

**Issue by ae6rt** [projectcalico/k8s-policy#30]
It would be helpful if this repository provided a paragraph of documentation on how the policy controller actually works.  What are the mechanics of how policy is enforced?  Is iptables somehow involved on a per k8s node basis?

**Comment by lxpollitt** [comment]
It uses the standard Calico enforcement policy mechanisms - which means, yes, iptables on each host.

We have a plan to consolidate all of our docs into a single location to make this information easier to glean rather than having to read around docs in several different repositories.

**Comment by ae6rt** [comment]
Thank you.  Am I right in guessing that the policy controller talks to Felix on each node to affect IP tables updates?

**Comment by lxpollitt** [comment]
The policy controller populates etcd with our high-level intent based data
model.  Felix monitors etcd and translates into the right iptables rules
required on each host for the workloads on that host.

**Comment by caseydavenport** [comment]
Assigning to @djosborne who is working on docs consolidation.
