### ISSUE TITLE
K8s-policy use security profile or security policy (tier)?

### ISSUE THREAD

**Issue by CBR09** [projectcalico/k8s-policy#34]
Hi,
First, thanks for your work, it's amazing. Today, I've tried calico network policy with k8s and it doesn't work, I wonder what mechanism k8s-policy use?, security profile or security policy(tier) or both?, I'm so confuse. Tomorrow I'll show what I explored and don't know why they don't work.
Thanks

**Comment by caseydavenport** [comment]
@CBR09 - The policy controller uses both tiered policies, as well as Profiles.

Policies are used for implementing `NetworkPolicy` objects from Kubernetes, while Profiles are used for the per-namespace ingress isolation behavior.

At the moment, calicoctl only supports Profiles, but you can view all policy directly using `etcdctl`.

e.g

```
etcdctl ls /calico/v1/policy --recursive
```

**Comment by CBR09** [comment]
@caseydavenport : Thanks you.
When I've created pod with label "role: backend" in namespace "cbr"
```
apiVersion: v1
kind: Pod
metadata:
  name: toilabackend
  namespace: cbr
  labels:
    role: backend
spec:
  containers:
    - name: web
      image: nginx 

```

I also watched etcd and realized no label to populate:

```
 /calico/v1/host/IRD-CAAS-G2-U4/workload/cni/85ec1e84935c10792cd6b359ff7e887ee8da4a1295dca207997a5f4cb22c7c19/endpoint/0f30660868e811e6bdaafa163edcff58
{"ipv6_gateway": null, "state": "active", "name": "cali0f30660868e", "ipv4_gateway": "10.40.31.146", "ipv6_nets": [], "profile_ids": ["k8s_ns.cbr"], "mac": "22:de:9f:16:90:64", "ipv4_nets": ["192.168.0.16/32"]}

```

Thus, security policy has no affect because only the policies that have matching selectors label are implemented. I have no idea why they didn't work.

Thanks

**Comment by CBR09** [comment]
It work now!, there are some issue in my cni plugin configure and version. After using cni-plugin v1.3.1 with config:
```
{
    "name": "k8s_ns.xxxxx",
    "type": "calico",
    "etcd_authority": "xxxxxx:4001",
    "log_level": "debug",
    "ipam": {
        "type": "calico-ipam"
    },
    "policy": {
        "type": "k8s",
	"k8s_api_root": "http://x.x.x.x:8080/api/v1/"
    }
}
```

Everything is fine!
Thanks
