### ISSUE TITLE
How to use k2s-policy with https API calls

### ISSUE THREAD

**Issue by maikotz** [projectcalico/k8s-policy#35]
Hi,

is there any documentation about how to use the policy controller on https enabled API's?

I only see that the controller.py checks if a ca is installed when doing the call.
    verify = CA_CERT_PATH if self.ca_crt_exists else False
            return session.get(path, verify=verify, stream=stream)

But no creation of any secrets, since it seems that that was the intention while looking at constants.py

    CA_CERT_PATH = "/var/run/secrets/kubernetes.io/serviceaccount/ca.crt"

In all examples it uses the insecure API on localhost:8080 but I'd like to separate the API servers from the worker nodes or use a HA infrastructure in the future. 

Thanks for all your work on the project!

**Comment by caseydavenport** [comment]
@maikotz Sorry there's little documentation in this area.

You can run against TLS enabled APIs, however you'd need to do one of two things:

1) If running as a static pod, you should be able to mount in the `ca.crt` and token from the host disk.
2) If running as a scheduled (non-static) pod, the kubelet should mount these both in for you, allowing you HTTPS access to the API.

**Comment by caseydavenport** [comment]
Raised #39 to cover documenting the policy controller config options.
