### ISSUE TITLE
Per-namespace profiles not used

### ISSUE THREAD

**Issue by cutwater** [projectcalico/k8s-policy#36]
Hi,

With pull request #33 per namespace policies were removed. 

It seems that currently the default namespace policy in k8s is ignored.
Policy-controller still creates per namespace profiles, but it looks that these profiles are not used.
Is such behaviour desired and correct?

Thanks.

**Comment by caseydavenport** [comment]
@cutwater - the per-namespace profiles should be in use when using v0.3.0.

There should be a "catch-all" tiered policy "no-match" that sends traffic to the next tier.

Could you share the output of `etcdctl ls /calico/v1/policy --recursive` so I can take a look at what policy has been programmed?

**Comment by cutwater** [comment]
@caseydavenport As I can see here policy-controller creates security profile for each k8s namespace which reflects namespace annotation `net.beta.kubernetes.io/network-policy`. But I don't see that it's used somewhere (e.g. in endpoints profiles). 

    $ etcdctl ls -r /calico/v1/policy
    /calico/v1/policy/profile
    /calico/v1/policy/profile/calico-k8s-network
    /calico/v1/policy/profile/calico-k8s-network/tags
    /calico/v1/policy/profile/calico-k8s-network/labels
    /calico/v1/policy/profile/calico-k8s-network/rules
    /calico/v1/policy/profile/k8s_ns.ccp
    /calico/v1/policy/profile/k8s_ns.ccp/tags
    /calico/v1/policy/profile/k8s_ns.ccp/labels
    /calico/v1/policy/profile/k8s_ns.ccp/rules
    /calico/v1/policy/profile/k8s_ns.default
    /calico/v1/policy/profile/k8s_ns.default/tags
    /calico/v1/policy/profile/k8s_ns.default/labels
    /calico/v1/policy/profile/k8s_ns.default/rules
    /calico/v1/policy/profile/k8s_ns.demo
    /calico/v1/policy/profile/k8s_ns.demo/tags
    /calico/v1/policy/profile/k8s_ns.demo/labels
    /calico/v1/policy/profile/k8s_ns.demo/rules
    /calico/v1/policy/profile/k8s_ns.kube-system
    /calico/v1/policy/profile/k8s_ns.kube-system/tags
    /calico/v1/policy/profile/k8s_ns.kube-system/labels
    /calico/v1/policy/profile/k8s_ns.kube-system/rules
    /calico/v1/policy/tier
    /calico/v1/policy/tier/k8s-network-policy
    /calico/v1/policy/tier/k8s-network-policy/metadata
    /calico/v1/policy/tier/k8s-network-policy/policy
    /calico/v1/policy/tier/k8s-network-policy/policy/k8s-policy-no-match

    $ etcdctl get /calico/v1/policy/profile/k8s_ns.demo/rules
    {"inbound_rules": [{"action": "allow"}], "outbound_rules": [{"action": "allow"}]}

    $ etcdctl get /calico/v1/host/k8s-02/workload/k8s/demo.nginx01-2362610013-9t1cn/endpoint/b52264c0750a11e6ac725254006e537b
{"name": "tapb52264c0750", "labels": {}, "state": "active", "ipv6_nets": [], "mac": "7a:29:ae:b1:37:ce", "ipv4_nets": ["10.233.71.82/32"], "profile_ids": ["calico-k8s-network"]}

Environment:
    $ kubectl --version
    Kubernetes v1.3.5+coreos.0

I'll try to deploy a minimal environment to have more information.

**Comment by caseydavenport** [comment]
@cutwater What does your CNI configuration look like? At the moment it is the CNI plugin that configures the `profile_ids` on an endpoint.

**Comment by cutwater** [comment]
@caseydavenport Thank you. You were right, configuration was invalid, which caused such unexpected behavior.
