### ISSUE TITLE
Multiple endpoints in workload

### ISSUE THREAD

**Issue by cutwater** [projectcalico/k8s-policy#37]
Hi,

Is it possible that calico workload can have multiple endpoints?
If yes, it seems that labels will be updated only for last returned endpoint, since it will overwrite previous value in cache. 

[pod.py](https://github.com/projectcalico/k8s-policy/blob/master/handlers/pod.py#L108)

    endpoints = client.get_endpoints(orchestrator_id="k8s")
    for ep in endpoints:
        endpoint_cache[ep.workload_id] = ep
        label_cache[ep.workload_id] = ep.labels

**Comment by caseydavenport** [comment]
@cutwater good spot :)

You're correct, in the generic case a single Calico workload can potentially have multiple endpoints.  However, when running under Kubernetes each Calico workload is mapped 1:1 with a k8s Pod, and should only ever have a single endpoint.  The `policy-controller` only works on endpoints which belong to the k8s orchestrator.

Do you have a use-case for multiple endpoints for a Kubernetes pod/workload?

**Comment by cutwater** [comment]
@caseydavenport Thank you for the clarification. It's not a valid case for k8s.
