### ISSUE TITLE
Current example without leader election

### ISSUE THREAD

**Issue by reAsOn2010** [projectcalico/k8s-policy#40]
It seems that the previous `examples/calico-policy-agent.yaml` have a leader election container, but now it's missing? We are doing k8s HA master and want to deploy several controllers.

**Comment by ae6rt** [comment]
@caseydavenport Explained this to me recently.  The new policy controller was converted to a replication controller with specifically one replica.  With only one replica, there is no need for an election.

**Comment by caseydavenport** [comment]
Yes, the example has changed since it is no longer a static pod, so failure is handled by Kubernetes.

I'm beginning to think it would be useful to keep an example of the static manifest, in case people want to continue deploying the policy-controller that way.

**Comment by caseydavenport** [comment]
Note that election is still supported (no code has been changed), it's just not implemented in the example manifest in this repo.

**Comment by reAsOn2010** [comment]
@caseydavenport Today I use current example yaml to deploy a new k8s cluster, but sadly it runs abnormally. The root cause is the network policy rc depends on kube-dns running well. When deploy a new cluster, the controller and DNS are all infrastructures in kube-system, so generally we cannot determine which one will be ready first. When you document this, maybe you need to add this hidden issue. THX~

**Comment by caseydavenport** [comment]
@reAsOn2010 - The example manifest _shouldn't_ rely on DNS running as well. I suspect something else is going on.  Could you raise another issue to track what you saw, and include details around the issue?

**Comment by reAsOn2010** [comment]
Sorry for late reply, here is the issue: https://github.com/projectcalico/k8s-policy/issues/42
