### ISSUE TITLE
Deploy policy controller as rc depends on kube-dns

### ISSUE THREAD

**Issue by reAsOn2010** [projectcalico/k8s-policy#42]
current example of deployment uses k8s service as API address:
```
            - name: K8S_API
              value: "https://kubernetes.default:443"
```
so if kube-dns is not well, the policy controller will not perform as expected.

When I deploy cluster using script, the kube-dns and calico policy controller will be deployed at same time. Then I can see the kube-dns is not working, the health check failed:
```
I0918 08:24:27.568409       1 logs.go:41] skydns: failure to forward request "read udp 172.16.4.0:33111->10.0.2.3:53: i/o timeout"
I0918 08:24:28.572025       1 dns.go:439] Received DNS Request:kubernetes.default.svc.cluster.local., exact:false
I0918 08:24:28.572128       1 dns.go:539] records:[], retval:[], path:[local cluster svc default kubernetes]
I0918 08:24:32.574080       1 logs.go:41] skydns: failure to forward request "read udp 172.16.4.0:58819->10.0.2.3:53: i/o timeout"
I0918 08:24:33.577189       1 dns.go:439] Received DNS Request:kubernetes.default.svc.cluster.local., exact:false
I0918 08:24:33.577217       1 dns.go:539] records:[], retval:[], path:[local cluster svc default kubernetes]
```

policy controller cannot call k8s api (seems to be DNS lookup failed):
```
ConnectionError: HTTPSConnectionPool(host='kubernetes.default', port=443): Max retries exceeded with url: /api/v1/pods (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f75588bc210>: Failed to establish a new connection: [Errno 110] Operation timed out',))
2016-09-18 08:26:04,661 5 WARNING Re-starting watch on resource: Pod
2016-09-18 08:26:04,661 5 ERROR Connection error querying: Namespace
Traceback (most recent call last):
  File "<string>", line 295, in _manage_resource
  File "<string>", line 381, in _sync_resources
  File "<string>", line 433, in _api_get
  File "site-packages/requests/sessions.py", line 480, in get
  File "site-packages/requests/sessions.py", line 468, in request
  File "site-packages/requests/sessions.py", line 576, in send
  File "site-packages/requests/adapters.py", line 437, in send
```

calicoctl profile
```
vagrant@master:~$ sudo ETCD_ENDPOINTS=http://192.168.205.10:2379 calicoctl profile show --detailed
+------+------+-----------------+-------------+-------------+-------+
| Name | Host | Orchestrator ID | Workload ID | Endpoint ID | State |
+------+------+-----------------+-------------+-------------+-------+
+------+------+-----------------+-------------+-------------+-------+
```

My guess is that, the network policy controller runs first, so the network is managed, but it cannot access k8s api, so no rule(profile) is generated, then all container's networks are broken. And the network failure keeps kube-dns failed, then the two component goes into crash loop and never recover.

If my guess is correct, deploying policy controller before kube-dns will reproduce the process.

@caseydavenport

**Comment by ae6rt** [comment]
Because the RC runs in the host network, your node must be able to resolve the Kubernetes master URL:

https://github.com/projectcalico/k8s-policy/blob/master/examples/policy-controller.yaml#L23

Try adding an /etc/hosts record for kubernetes as a test, where a.b.c.d is the address of your master

```
a.b.c.d kubernetes
```

**Comment by caseydavenport** [comment]
Yep - the DNS pod won't work until the policy controller has run and configured the profile, etc for the kube-system Namespace.

In the example manifest, the policy controller uses `https://kubernetes.default:443`, which it expects to resolve to the Master's service clusterIP.  

It also sets `CONFIGURE_ETC_HOSTS` to true, which will tell the policy controller to set up the container's resolv.conf to resolve `kubernetes.default` to the service clusterIP without needing DNS access, in a similar way to what ae6rt says above.

The fact that you're seeing "operation timed out" indicates to me that it's probably not the name lookup that is failing.  I'd guess it's probably the Service clusterIP not being handled properly.  Do you have the kube-proxy running on each node in the cluster?

You should be able to check if the proxy is working by trying to curl the address on the host:

```
curl -k https://<master_service_vip>:443
```

I'd expect an "Unauthorized" response.

**Comment by reAsOn2010** [comment]
Ah.. @caseydavenport you are right, `/etc/hosts` is configured as expected. Proxy is running and I can see the rules in iptables of kubernetes svc
```
-A KUBE-SEP-AJDQ5GXJFICQGLFW -s 192.168.205.10/32 -m comment --comment "default/kubernetes:https" -j KUBE-MARK-MASQ
-A KUBE-SEP-AJDQ5GXJFICQGLFW -p tcp -m comment --comment "default/kubernetes:https" -m recent --set --name KUBE-SEP-AJDQ5GXJFICQGLFW --mask 255.255.255.255 --rsource -m tcp -j DNAT --to-destination 192.168.205.10:6443

-A KUBE-SERVICES -d 10.254.0.1/32 -p tcp -m comment --comment "default/kubernetes:https cluster IP" -m tcp --dport 443 -j KUBE-SVC-NPX46M4PTMTKRN6Y

-A KUBE-SVC-NPX46M4PTMTKRN6Y -m comment --comment "default/kubernetes:https" -m recent --rcheck --seconds 180 --reap --name KUBE-SEP-AJDQ5GXJFICQGLFW --mask 255.255.255.255 --rsource -j KUBE-SEP-AJDQ5GXJFICQGLFW
-A KUBE-SVC-NPX46M4PTMTKRN6Y -m comment --comment "default/kubernetes:https" -j KUBE-SEP-AJDQ5GXJFICQGLFW
```

directly visiting the target got correct response
```
vagrant@node-1:~$ curl -k https://192.168.205.10:6443
Unauthorized
```

but using service vip got no response and timed out.
```
vagrant@node-1:~$ curl -k https://10.254.0.1:443
```

I'll use tcpdump to figure out why. And it's not policy controller deployment problem, so close~
Many thanks! @caseydavenport @ae6rt

**Comment by reAsOn2010** [comment]
![image](https://cloud.githubusercontent.com/assets/1191377/18620787/39d022bc-7e4c-11e6-811c-f962559bc325.png)
In the packet flow, some unexpected src ip existed. The `10.0.2.15` ip is that vagrant machine used as NAT to access external Internet, and the SYN packet is send from this ip... So the problem must be existed in my cluster network environment~

**Comment by caseydavenport** [comment]
@reAsOn2010 -  Yeah, I've hit that issue before on vagrant.  The kube-proxy will use the source address used by the default route when sending traffic from the host / a pod with host networking.

I _think_ (if I remember correctly) the fix is to set the `--cluster-cidr` flag on the kube-proxy to the full pod CIDR you've chosen.

```
      --cluster-cidr="": The CIDR range of pods in the cluster. It is used to bridge traffic coming from outside of the cluster. If not provided, no off-cluster bridging will be performed.
```

I think this will ensure that the traffic gets masqueraded as the correct source address.  See the configuration here: https://github.com/projectcalico/calico-containers/blob/master/docs/cni/kubernetes/vagrant-coreos/cloud-config/node-config.yaml#L73

Pretty sure that vagrant setup handles Service traffic properly.
