### ISSUE TITLE
Examples do not work

### ISSUE THREAD

**Issue by microadam** [projectcalico/k8s-policy#6]
Trying to get this working, have followed everything on here:

https://github.com/projectcalico/calico-containers/blob/master/docs/cni/kubernetes/NetworkPolicy.md

I have annotated my namespace with the following:

```
kubectl annotate ns default "net.alpha.kubernetes.io/network-isolation=yes" --overwrite=true
```

Using the examples in the `examples` folder (and changing `inbound` to `ingress`), when I run:

```
./policy create -f backend-policy.yaml
```

I see the following in the logs of the policy agent:

```
2016-03-21 21:10:14,884 6 INFO Adding new network policy: (u'two', u'backend-policy')
2016-03-21 21:10:14,885 6 INFO Found 1 ingress rules
2016-03-21 21:10:14,891 6 INFO Updated policy 'two.backend-policy' for NetworkPolicy (u'two', u'backend-policy')
```

When I run:

```
kubectl exec backend-1e43i -- wget http://backend.default.svc.cluster.local -T 1 -t 1 -q -O - 2>&1
```

the request fails (setting the annotation to `network-isolation=no` makes that command work, so something is happening).

Any thoughts as to if I am doing something wrong? 

Thanks

**Comment by caseydavenport** [comment]
Hey @microadam 

Sorry about the `inbound` -> `ingress` typo!  I'll make sure to get that fixed up.

Aside from that though, it looks like your namespace isolation is behaving as expected.  

If you take a look at `backend-policy.yaml` [here](https://github.com/projectcalico/k8s-policy/blob/master/examples/policy/backend-policy.yaml#L12), you'll see that it only allows from pods with the label `tier: frontend`, so I wouldn't expect this to work:

```
kubectl exec backend-1e43i wget http://backend.default.svc.cluster.local -T 1 -t 1 -q -O - 2>&1
```

I would however expect something like this to work (note that this is executed in a frontend pod):
```
kubectl exec frontend-xxxxx wget http://backend.default.svc.cluster.local -T 1 -t 1 -q -O - 2>&1
```

To allow east-west communication between backend pods, you could add another `ingress` rule which allows it.  

Let me know if that makes sense.

**Comment by microadam** [comment]
Hi @caseydavenport!

Thanks for your reply, apologies, you are correct, I was testing from the backend pod, rather than the frontend pod. However, even from the frontend pod I have the same result.

Once I have run `./policy create -f backend.yml`, if I check the output of `calicoctl profile k8s_ns.default rule show` I have the following:

```
Inbound rules:
   1 deny
Outbound rules:
   1 allow
```
I would have thought this would have changed? (no other profiles have been created, so I assume that is how this is supposed to work). Its almost as though the profile creation isn't actually communicating with the calico backend. Any thoughts as to what might cause it? Let me know if there is any information you require in order to help debug the issue.

Thanks alot!

**Comment by caseydavenport** [comment]
Sorry - it's a bit confusing at the moment as we work to finish off much of the extra bits and pieces around the edges in terms of policy support.  

The policy agent actually configures a new Calico structure called "policies", which aren't exposed through `calicoctl` yet.  That profile looks correct for the namespace assuming isolation is enabled, and I wouldn't expect it to change when NetworkPolicy objects are configured.

`calicoctl` support is in the pipeline, but in the meantime you can check that things are being configured via etcdctl.

For example:
```
etcdctl ls --recursive /calico/v1/policy/tier
```

Should return any configured policies.

One place I'd check first is to make sure you're using `calico/node:v0.17.0-k8s-policy` as this is the calico/node version that supports the new k8s policy.  Without this, `NetworkPolicy` objects won't work correctly.  

We should also have a v0.18.0 release out this week that will support it.

**Comment by caseydavenport** [comment]
I also noticed that your `NetworkPolicy` appears to be in the namespace called `two`, whereas you're trying to access services in the `frontend` namespace.  A `NetworkPolicy` can be applied to pods within the same namespace as it, so I'd double check that it exists in the same namespace as your backend pods.

**Comment by microadam** [comment]
Hi Casey, thanks for all your suggestions. I had actually tweaked the examples slightly (hence the two). So I have gone back to using the exact examples (but changing `inbound` for `ingress`).

I did the following:

```
kubectl create -f examples/manifests/
kubectl exec frontend-2i8jx -- wget http://backend.default.svc.cluster.local -T 1 -t 1 -q -O - 2>&1 # THIS WORKED
kubectl annotate ns default "net.alpha.kubernetes.io/network-isolation=yes" --overwrite=true
kubectl exec frontend-2i8jx -- wget http://backend.default.svc.cluster.local -T 1 -t 1 -q -O - 2>&1 # THIS NOW DOESNT WORK
./policy create -f backend-policy.yml # with inbound changed to ingress
```

At this point this appears in the logs:

```
2016-03-23 08:07:28,643 6 INFO Adding new network policy: (u'default', u'backend-policy')
2016-03-23 08:07:28,644 6 INFO Found 1 ingress rules
2016-03-23 08:07:28,649 6 INFO Updated policy 'default.backend-policy' for NetworkPolicy (u'default', u'backend-policy')
```

And I have this stored in `etcd`:
```
/calico/v1/policy/tier/k8s-network-policy
/calico/v1/policy/tier/k8s-network-policy/metadata
/calico/v1/policy/tier/k8s-network-policy/policy
/calico/v1/policy/tier/k8s-network-policy/policy/default.backend-policy
-----
/calico/v1/policy/tier/k8s-network-policy/policy/default.backend-policy:
{"id": "default.backend-policy", "outbound_rules": [{"action": "allow"}], "order": 10, "inbound_rules": [{"action": "allow", "src_selector": "tier == 'frontend' && calico/k8s_ns == 'default'", "protocol": "tcp", "dst_ports": [80]}], "selector": "tier == 'backend' && calico/k8s_ns == 'default'"}
```

Output from `calicoctl profile k8s_ns.default rule show`:

```
Inbound rules:
   1 deny
Outbound rules:
   1 allow
```

Now running:

```
kubectl exec frontend-2i8jx -- wget http://backend.default.svc.cluster.local -T 1 -t 1 -q -O - 2>&1
```

still doesn't work unfortunately. I have confirmed I am running `calico/node:v0.17.0-k8s-policy`.

If you follow the same steps above, does it work for you? I can only assume I am doing something wrong, or I possibly have the wrong version of something somewhere (have confirmed I am running `v1.1.0` of `calico` and `calico-ipam`). Am on Kubernetes `1.2.0` and docker `1.10.3` if that makes any difference.

Thanks a lot for your assistance!

**Comment by microadam** [comment]
Upgraded to `v.0.1.2`, all appears to be working, thanks a lot!
