### ISSUE TITLE
policy controller SSL problems with CA chain certs

### ISSUE THREAD

**Issue by redbaron** [projectcalico/k8s-policy#67]
controller can't connect to Etcd servers

```
2017-02-03 15:55:23,382 6 INFO Leader election enabled? False
2017-02-03 15:55:23,382 6 DEBUG Attempting to remove old tier k8s-network-policy
Traceback (most recent call last):
  File "<string>", line 516, in <module>
  File "<string>", line 141, in run
  File "site-packages/pycalico/datastore.py", line 901, in delete_policy_tier
  File "site-packages/etcd/client.py", line 610, in delete
  File "site-packages/etcd/client.py", line 860, in wrapper
etcd.EtcdConnectionFailed: Connection to etcd failed due to SSLError(SSLError(1, u'[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)'),)
controller returned -1
```
we tripple checked all certs and they are fine, my only version would be that it is related to our etcd server and client certs being signed by intermediary CA, so that whole CA chain has multiple certs. It seems that it causes problems for python etcd client as it produces error like one above.

We had similar problem with `calico/node:v1.0.2`, but updating that image to v1.1.0-rc2 solved the problem as `/bin/startup` which was failing with similar error was replaced with Go version.

It is possible that python lib urllib3 is problem: https://github.com/shazow/urllib3/issues/878

Do you know if there is a workaround to continue to use certs, but disable  cert validation maybe? It is not ideal, but would allow us to start using Calico in our setup

**Comment by stongo** [comment]
Also hit this same issue

**Comment by redbaron** [comment]
what we found, is that setup suitable for Go wasn't enough for curl & python. It was related to CA chain, but not in the way I originally thought.

Basically to make it work for curl & python we had to add full CA chain to the list of trusted certs, while Go seems to be happy to report successful validation on if just one cert from CA chain is trusted.

So check you connection with curl,if it is unhappy, keep playing with your SSL setup until curl is happy, then Calico will work too

**Comment by stongo** [comment]
My Etcd client certificates and ca.pem work in curl and all other k8s services. They are generated by Vault's PKI backend. 
May be a bit premature to close this, but I can open another issue with more debugging if that would be helpful.
It is quite difficult to debug though with such a generic error message

**Comment by redbaron** [comment]
we do use vault PKI too and Calico 2.0.2 release definitely works for us

**Comment by stongo** [comment]
Mind sharing your config and k8s manifest?

**Comment by redbaron** [comment]
you can have a look at `kube-aws` which we use. When certs are generated, we place them as following:

1. vault root CA and it's chain go to `ca.pem`
2. vault PKI intermediate CA and service cert go to `etcd.pem`
3. vault PKI intermediae CA ans client cert go to `etcd-client.pem`

also make sure that when you mount *client* PKI roles, you set `server_flag=false`

**Comment by nilsher** [comment]
Had the same problem. Adding root CA into ca file worked. Python urllib3 which is broken or should be fixed imho. Root CA shouldn't be required.
