### ISSUE TITLE
calico-policy-controller cannot create profile object

### ISSUE THREAD

**Issue by Huang-Wei** [projectcalico/k8s-policy#72]
After running `calico/kube-policy-controller:v0.4.0` for a while, I noticed that when a namespace was created, it didn't create profile properly:

```
$ calicoctl get profile | grep hweicdl
$ kubectl create ns hweicdl
namespace "hweicdl" created
$ calicoctl get profile | grep hweicdl
(no output here)
```

And obviously (works for default and kube-system) it doesn't function since a certain moment:

```
$ calicoctl get profile | egrep "default|kube-system"
k8s_ns.default
k8s_ns.kube-system
```

This resulted in a severe situation that all pods in problematic namespace(s) cannot be pinged. (see comment [here](https://github.com/projectcalico/calicoctl/issues/1377#issuecomment-284669198))

Restarting calico-policy-controller resolved the issue. But I'm not sure if it's fixed in latest `calico/kube-policy-controller:v0.5.2` image.

(BTW: I didn't see supicious log in calico-policy-controller.)

**Comment by fasaxc** [comment]
@Huang-Wei Please can you switch to the latest v0.5.2 image to see if that solves the problem?

**Comment by Huang-Wei** [comment]
@fasaxc Will do and let you know.

**Comment by tmjd** [comment]
@Huang-Wei There has been another release of k8s-policy https://github.com/projectcalico/k8s-policy/releases/tag/v0.5.4 which specifically addresses an issue where the policy controller would fall out of date.

I'm going to close this issue for now, if you upgrade to v0.5.4 and still are having this issue then please reopen this issue or create a new one.  Thanks.

**Comment by Huang-Wei** [comment]
@tmjd I've been switched to 0.5.2 for a while, and everything works fine so far. Thanks!
