### ISSUE TITLE
policy-controller uses LIST, not GET

### ISSUE THREAD

**Issue by djosborne** [projectcalico/k8s-policy#75]
Calico policy controller code refers to `GET_URLS` for resources in `constants.py`.

I've been toying around with RBAC rules and it seems like the request is actually a `LIST` request.

Either we're hitting the wrong URL and making LIST requests by mistake, or we should rename the param to be less confusing

**Comment by caseydavenport** [comment]
I think this is just a rename to "RESOURCE_URLS" or something like that.  They're used for both operations. 

This is also really low priority.

**Comment by caseydavenport** [comment]
Closing as wontfix - this is just a minor naming tweak, doesn't require an issue.
