### ISSUE TITLE
Link Kubernetes Namespace and Calico IP Pool

### ISSUE THREAD

**Issue by tmjd** [projectcalico/k8s-policy#78]
This is a feature request that allows linking a Kubernetes Namespace and Calico IP Pool.
This would cause a pod created in the namespace to use IP addresses from the linked IP Pool.

**Comment by caseydavenport** [comment]
@tmjd going to close this guy since I don't think this is the right repository - could you re-open in either `projectcalico/calico` or `projectcalico/cni-plugin`?

**Comment by tmjd** [comment]
Created https://github.com/projectcalico/calico/issues/622 instead
