### ISSUE TITLE
Should have TLS FV tests including IP SANs

### ISSUE THREAD

**Issue by fasaxc** [projectcalico/k8s-policy#90]
Looks like we have a gap in our testing of the policy agent in that we don't have tests for TLS or IP SAN support when talking to etcd or the k8s API server.  (The two communication channels use different libs so we need to test both.)

TLS might be covered in another repo (which is fine), but #69 shows that we have a  gap.

**Comment by caseydavenport** [comment]
Now that we're using k8s `client-go` and Calico `libcalico` for both API + etcd access I think this function is tested in other repos.
