### ISSUE TITLE
Dose kube-policy-controller work with etcdv3?

### ISSUE THREAD

**Issue by jeffchanjunwei** [projectcalico/k8s-policy#92]
I deploy a k8s with kargo, and add the policy controller in the cluster. But the policy controller pod can not be created succefulley. The errors are show bellow.

_# kubectl logs calico-policy-controller-3632650762-qdb8j -n kube-system_
```
2017-04-27 03:39:18,304 6 INFO Configuring /etc/hosts
2017-04-27 03:39:18,305 6 INFO Appended 'kubernetes.default  -> 10.254.0.1' to /etc/hosts
2017-04-27 03:39:18,306 6 INFO Beginning execution
2017-04-27 03:39:18,306 6 INFO Leader election enabled? False
Traceback (most recent call last):
  File "<string>", line 516, in <module>
  File "<string>", line 141, in run
  File "site-packages/pycalico/datastore.py", line 901, in delete_policy_tier
  File "site-packages/etcd/client.py", line 610, in delete
  File "site-packages/etcd/client.py", line 860, in wrapper
etcd.EtcdConnectionFailed: Connection to etcd failed due to MaxRetryError("HTTPConnectionPool(host='127.0.0.1', port=2379): Max retries exceeded with url: /v2/keys/calico/v1/policy/tier/k8s-network-policy?recursive=true&dir=true (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbf8cee1f50>: Failed to establish a new connection: [Errno 111] Connection refused',))",)
controller returned -1
```

In the etcd of calico, I also cann't find any info any profile about the namespaces which have already been created in k8s.

_# calicoctl get profile_
```
NAME                 
calico-k8s-network
```

_# kubectl get ns_
```
NAME          STATUS    AGE
default       Active    2d
kube-system   Active    2d
```

_Versions_
```
kube-policy-controller: >= v0.5.2
k8s: v1.5.1
etcd: "etcdserver":"3.0.17","etcdcluster":"3.0.0"
calico/node: v1.1.0
cni-plugin: v1.6.1
```

How can I fix it？I doubt that the policy controller cann't work with etcdv3, or the env of etcd in the pod dostn't work, so it can not write sth into etcd.

**Comment by tmjd** [comment]
Yeah there should be no problem with etcdv3, though Calico will just use the v2 API that the etcdv3 server provides.

Your log message indicates that the policy-controller is trying to reach localhost for etcd.  That is not what I would expect but is not necessarily wrong, do you know how your etcd is deployed? I think it is possible to run an etcd proxy on all hosts which would allow a localhost connection to work.

**Comment by jeffchanjunwei** [comment]
@tmjd thx. I have verified its the problem of etcd address.
